version: '3.8'

services:
  monopoly-game:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monopoly-online
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOST=0.0.0.0
    restart: unless-stopped
    networks:
      - monopoly-network

networks:
  monopoly-network:
    driver: bridge
